---
- name: Install Zsh
  apt: pkg=zsh state=latest
  become: True
- name: set zsh as default shell
  shell: "chsh -s /bin/zsh {{ user }}"
  become: True
- name: default zshrc to prevent problems
  shell: touch ~/.zshrc
  become: false
- name: Install Tmux
  apt: pkg=tmux state=latest
  become: True
