---
- hosts: dilbert
  vars:
    user: travis
    user_home: "/home/travis" 
    rvm1_rubies:
          - 'ruby-2.1.3'
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      sudo: True
      notify:
      - restart ntpd
    - name: Set timezone to London
      shell: timedatectl set-timezone Europe/London
      sudo: True
  roles:
      #    - db.basic_utils
      ##   - db.known_hosts
      #    - db.pkg_mgt
      #    - db.shell
      #    - db.node
      #    - db.adv_utils
      #    - dotfiles
    - docker
    - db.java
#    - db.gvm
    - { role: rvm_io.rvm1-ruby, sudo: true }
    - db.cucumber
    - db.leiningen 
  handlers:
    - name: restart ntpd
      shell: sudo ntpd
