---
- hosts: dilbert
  vars:
    user: travis
    user_home: "/home/travis" 
    rvm1_rubies:
          - 'ruby-2.1.3'
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      sudo: True
      notify:
      - restart ntpd
    - name: Set timezone to London
      shell: timedatectl set-timezone Europe/London
      sudo: True
      when: ansible_env.CI != 'true'
  roles:
    - db.basic_utils
    - {role: db.known_hosts when: ansible_env.CI != 'true'}
    - db.pkg_mgt
    - db.shell
    - db.node
    - db.adv_utils
    - dotfiles
    - {role: docker when: ansible_env.CI != 'true'}
    - db.java
    - { role: rvm_io.rvm1-ruby, sudo: true }
    - db.cucumber
    - db.leiningen 
  handlers:
    - name: restart ntpd
      shell: sudo ntpd
