---
- hosts: localhost
  connection: local
  vars:
    user: darrenbuse
    user_home: "/Users/darrenbuse/"
    hostname: "bob"
    work_apps: false
  become: no
  tasks:
      - name: set hostname
        shell: 'scutil --set HostName "{{ hostname }}" && scutil --set LocalHostName "{{ hostname }}"'
        become: True
      - name: set hostname in hosts file
        lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {hostname}' 
        become: True
  roles:
    - db.osx-apps
    - db.dotfiles
    - db.my-utils
    
