---
- name: create known_hosts if missing
  file: path=/home/darren/.ssh/known_hosts state=touch
  sudo_user: darren
  sudo: True
- name: Add Github key. 
  shell: ssh-keygen -R github.com && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  sudo_user: darren
  sudo: True
- name: Add bitbucket key. 
  shell: ssh-keygen -R bitbucket.org && ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
  sudo_user: darren
  sudo: True
- name: Checkout dotfiles from git
  shell: git clone git@bitbucket.org:darrenbuse/dotfiles.git --recursive chdir=/home/darren/ creates=/home/darren/dotfiles/
  sudo_user: darren
  sudo: True
- name: Link files
  shell: /home/darren/dotfiles/link.sh
  sudo_user: darren
  sudo: True
