---
- name: Checkout dotfiles from git - is ssh agent running?
  git: repo=https://github.com/darrenbuse/dotfiles.git recursive=yes dest="{{ user_home  }}/dotfiles/" accept_hostkey=yes update=no
  sudo: True
  sudo_user: "{{ user }}"
  
- name: Link files - takes a while to clone YCM
  shell: "/bin/sh -c \"{{ user_home }}/dotfiles/link.sh\""
  sudo_user: "{{ user }}"
  sudo: True

- name: Setup osx dotfile settings.
  shell: "zsh -c \"source {{ ansible_env.HOME  }}/dotfiles/osx/bootstrap.sh\""
  when: ansible_os_family == 'Darwin'
#
#
#- name: install you compleate me on Ubuntu
#  apt: name=vim-youcompleteme
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#  sudo: True

