---
- name: Checkout dotfiles from git - is ssh agent running?
  git: repo=https://github.com/darrenbuse/dotfiles.git recursive=yes dest="{{ ansible_env.HOME  }}/dotfiles/" accept_hostkey=yes update=yes
  sudo: no
  
- name: Link files
  shell: "zsh -c \"source {{ ansible_env.HOME }}/dotfiles/link.sh\""
  sudo_user: "{{ user }}"
  sudo: True

- name: install you compleate me on Ubuntu
  apt: name=vim-youcompleteme
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  sudo: True

