---
- name: Checkout dotfiles from git
  git: repo=ssh://git@bitbucket.org/darrenbuse/dotfiles.git recursive=yes dest="/home/{{ user  }}/dotfiles/" accept_hostkey=yes update=yes
  sudo: no
  
- name: Link files
  shell: "zsh -c \"source /home/{{ user }}/dotfiles/link.sh\""
  sudo_user: "{{ user }}"
  sudo: True
