---
- name: Checkout dotfiles from git
  git: repo=ssh://git@bitbucket.org/darrenbuse/dotfiles.git recursive=yes dest="{{ lookup('env','HOME')  }}/dotfiles/" accept_hostkey=yes update=yes
  sudo: no
  
- name: Link files
  shell: "zsh -c \"source {{ lookup('env','HOME') }}/dotfiles/link.sh\""
  sudo_user: "{{ user }}"
  sudo: True
