---
- name: Checkout dotfiles from git - is ssh agent running?
  git: repo=https://github.com/darrenbuse/dotfiles.git recursive=yes dest="{{ user_home  }}/dotfiles/" accept_hostkey=yes update=yes
  sudo: True
  sudo_user: "{{ user }}"
  
- name: Link files - takes a while to clone YCM
  shell: "zsh -c \"source {{ user_home }}/dotfiles/link.sh\""
  sudo_user: "{{ user }}"
  sudo: True

#- name: install you compleate me on Ubuntu
#  apt: name=vim-youcompleteme
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#  sudo: True

