# -*- mode: ruby -*-
# vi: set ft=ruby :
API_VERSION = "2"

Vagrant.configure(API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
  end 

  config.vm.box = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.define "cache" do |cache|
    cache.vm.provider "virtualbox" do |devmastervb|
        devmastervb.memory=256
        devmastervb.cpus=1
    end
    cache.vm.network "private_network", ip: "10.12.0.1", netmask: "255.255.0.0"
    cache.vm.provision "shell", inline: "sudo apt-get install -y squid-deb-proxy"
    cache.vm.provision "shell", inline: "sudo echo ppa.launchpad.net >> /etc/squid-deb-proxy/mirror-dstdomain.acl"
    cache.vm.synced_folder "../apt-cache", "/var/cache/apt-cacher-ng", :mount_options => ["dmode=777","fmode=777"] 
    cache.vm.provision "file", source: './squid-deb-proxy.conf', destination: '/home/vagrant/squid-deb-proxy.conf'
    cache.vm.provision "shell", inline: "sudo cp /home/vagrant/squid-deb-proxy.conf /etc/squid-deb-proxy/squid-deb-proxy.conf"
    cache.vm.provision "shell", inline: "sudo service squid-deb-proxy restart"
  end

  config.vm.define "devmaster" do |devmaster|
    devmaster.vm.provider "virtualbox" do |devmastervb|
        devmastervb.memory=3048
        devmastervb.cpus=5
        devmastervb.customize ["modifyvm", :id, "--uart1", "0x3f8", "4"]
        devmastervb.customize ["modifyvm", :id, "--uartmode1", "server", "/tmp/my_tty"]
    end

    devmaster.vm.host_name = "devmaster"
    devmaster.vm.network "private_network", ip: "10.12.0.2", netmask: "255.255.0.0"
    devmaster.ssh.forward_agent = true
    devmaster.vm.provision "file", source: '~/.ssh/id_rsa', destination: '/home/vagrant/.ssh/id_rsa'
    devmaster.vm.provision "ansible" do |ansible|
        ansible.playbook = "../devmaster.yml"
        ansible.verbose =  'v'
        ansible.raw_ssh_args = ["-o UserKnownHostsFile=/dev/null"]
    end

    devmaster.vm.synced_folder "../../..", "/home/vagrant/Projects", nfs: true, nfs_udp: false
 end
end
