---
- homebrew_tap: tap=caskroom/cask
- homebrew: name=brew-cask state=latest
- homebrew_tap: tap=caskroom/versions
- homebrew_cask: name=google-chrome-beta state=latest
- homebrew_cask: name=flux state=latest
- homebrew_cask: name=gitx state=latest
- homebrew_cask: name=google-drive state=latest
- homebrew_cask: name=lastpass-universal state=latest
- homebrew_cask: name=spotify state=latest
- homebrew_cask: name=sonos state=latest
- homebrew_cask: name=virtualbox state=latest
- homebrew_cask: name=vagrant state=latest
- homebrew_cask: name=java state=latest
- homebrew_cask: name=atom state=latest
- homebrew_cask: name=intellij-idea state=latest
- homebrew_cask: name=disk-inventory-x state=latest
- homebrew_cask: name=evernote state=latest
- homebrew_cask: name=skype state=latest
- homebrew_cask: name=lighttable state=latest
- homebrew_cask: name=sophos-anti-virus-home-edition state=latest
- homebrew: name=tmux state=latest
- homebrew: name=wget state=latest
- homebrew: name=zsh state=latest
- homebrew: name=tig state=latest
- homebrew: name=node state=latest
- homebrew: name=vim state=latest
- homebrew: name=ctags-exuberant state=latest
- name: set zsh as default shell
  shell: "chsh -s /bin/zsh {{ user  }}"
- name: Setup osx dotfile settings.
  shell: "zsh -c \"source {{ ansible_env.HOME  }}/dotfiles/osx/bootstrap.sh\""
- name: Install ssh-copy-id
  copy: src="ssh-copy-id.sh" dest="{{ user_home }}/bin/ssh-copy-id" mode="0744" 
