---
- name: Install curl
  apt: pkg=curl state=latest
  sudo: True
- name: docker key
  apt_key: keyserver=pgp.mit.edu id=58118E89F3A912897C070ADBF76221572C52609D
  sudo: true
- name: docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-vivid main' state=present
  sudo: true
- name: install docker
  apt: pkg=docker-engine
  sudo: True
- name: Run docker without using sudo
  shell: "gpasswd -a {{ user }} docker && service docker restart"
  sudo: True
