---
- name: install docker
  shell: curl -s https://get.docker.io/ubuntu/ | sudo sh creates=/usr/bin/docker
  sudo: True
- name: Run docker without using sudo
  shell: gpasswd -a vagrant docker && service docker restart
  sudo: True
- name: install pip for docker-py
  apt: pkg=python-pip state=latest
  sudo: True
- name: install docker-py
  pip: name=docker-py
  sudo: True
- name: Check if base image is cached
  shell: "[ -f /cache/ubuntu.tar  ] && echo 'Found' || echo ''"
  register: ubuntu_cache_exists
- name: Grab cached base image
  shell: docker load < /cache/ubuntu.tar
  sudo: True
  when: ubuntu_cache_exists.stdout
- name: Grab base image
  shell: docker pull ubuntu:saucy
  sudo: True
