
---
- name: Github keys
  shell: ssh-keyscan -H github.com >> /home/vagrant/.ssh/known_hosts
  sudo: false
- name: Bitbucket Keys
  shell: ssh-keyscan -H bitbucket.org >> /home/vagrant/.ssh/known_hosts
  sudo: false
