# -*- mode: ruby -*-
# vi: set ft=ruby :
API_VERSION = "2"

Vagrant.configure(API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
  end 

  config.vm.box = 'https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.define "dilbert" do |dilbert|
    dilbert.vm.provider "virtualbox" do |dilbertvb|
        dilbertvb.memory=6096
        dilbertvb.cpus=5
    end

    dilbert.vm.host_name = "dilbert"
    dilbert.vm.network "private_network", ip: "10.12.0.2", netmask: "255.255.0.0"
    dilbert.ssh.forward_agent = true
    dilbert.vm.provision "file", source: '~/.ssh/id_rsa', destination: '~/.ssh/id_rsa'
    dilbert.vm.provision "file", source: '~/.location', destination: '~/.location'
    dilbert.vm.provision "file", source: '~/.env', destination: '~/.env'
    dilbert.vm.provision "file", source: './enviroment', destination: '~/enviroment'
    dilbert.vm.provision "shell", inline: 'sudo mv /home/vagrant/enviroment /etc/environment'
    dilbert.vm.provision "shell", inline: 'sudo chown root:root /etc/environment'
    dilbert.vm.provision "shell", inline: 'sudo apt-get update'
    dilbert.vm.provision "shell", inline: 'sudo apt-get upgrade -y'
    dilbert.vm.provision "shell", inline: 'sudo apt-get purge python-requests -y && sudo apt-get install python-requests python-pip -y'

    dilbert.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
              user: "vagrant",
              user_home: "/home/vagrant"
              }
        ansible.playbook = "../vm.yml"
        ansible.verbose =  'v'
        ansible.raw_ssh_args = ["-o UserKnownHostsFile=/dev/null"]
    end

    dilbert.vm.synced_folder "/Volumes/Share/Projects/", "/home/vagrant/Projects", nfs: true, nfs_udp: false, nfs_options: "-mapall=1000:1000"
    home = ENV["HOME"]
    dilbert.vm.synced_folder home + "/notes", "/home/vagrant/notes", nfs: true, nfs_udp: false
    dilbert.vm.synced_folder home + "/Dropbox", "/home/vagrant/Dropbox", nfs: true, nfs_udp: false
 end
end
